#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

COMMON="$SCRIPT_DIR/config.common"
LOCAL="$SCRIPT_DIR/config.local"

TARGET_DIR="$HOME/.ssh"
TARGET="$TARGET_DIR/config"

mkdir -p "$TARGET_DIR"
chmod 700 "$TARGET_DIR"

timestamp="$(date +%Y%m%d-%H%M%S)"

if [[ -f "$TARGET" ]]; then
  cp "$TARGET" "$TARGET.bak.$timestamp"
  echo "✅ Backup: $TARGET.bak.$timestamp"
fi

if [[ ! -f "$COMMON" ]]; then
  echo "❌ Missing common config: $COMMON"
  exit 1
fi

tmp="$(mktemp)"
{
  echo "# ========================================="
  echo "# AUTOGENERATED by ssh-config-sync.sh"
  echo "# Source: $COMMON"
  [[ -f "$LOCAL" ]] && echo "# Local overrides: $LOCAL"
  echo "# Generated at: $timestamp"
  echo "# ========================================="
  echo
  cat "$COMMON"
  echo
  if [[ -f "$LOCAL" ]]; then
    echo "# -------- LOCAL OVERRIDES --------"
    cat "$LOCAL"
    echo
  fi
} > "$tmp"

mv "$tmp" "$TARGET"
chmod 600 "$TARGET"
echo "✅ Synced to $TARGET"
